local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("Chronicles - Wars", "enUS", true, true)

if L then
    L["First War label"] = "The First War"
    L["First War page 1"] = '<HTML><BODY><BR/><BR/><H1 align="center">First War</H1></BODY></HTML>'
    
    L["War of the ancient label"] = "The War of the ancient"
    L["War of the ancient page 1"] = '<HTML><BODY><BR/><BR/><H1 align="center">War of the ancient page 1</H1></BODY></HTML>'
    L["War of the ancient page 2"] = '<HTML><BODY><BR/><BR/><H1 align="center">War of the ancient page 2</H1></BODY></HTML>'    
    
    L["War of the Three Hammers label"] = "The War of the Three Hammers"
    L["War of the Three Hammers page 1"] =
        '<HTML><BODY><p>The <a href="/Dwarf" title="Dwarf">dwarves</a> of <a href="/Ironforge" title="Ironforge">Ironforge Mountain</a> lived in peace for many long centuries. However, their society grew too large within the confines of their mountain cities. Though the mighty High King, <a href="/Modimus_Anvilmar" title="Modimus Anvilmar">Modimus Anvilmar</a>, ruled over all dwarves with justice and wisdom, three powerful factions had arisen amongst the dwarven society. </p><p>The <a href="/Bronzebeard_Clan" class="mw-redirect" title="Bronzebeard Clan">Bronzebeard</a> clan, ruled by Thane <a href="/Madoran_Bronzebeard" title="Madoran Bronzebeard">Madoran Bronzebeard</a>, held close ties to the High King and stood as the traditional defenders of Ironforge Mountain. The <a href="/Wildhammer_Clan" class="mw-redirect" title="Wildhammer Clan">Wildhammer</a> clan, ruled by Thane <a href="/Khardros_Wildhammer" title="Khardros Wildhammer">Khardros Wildhammer</a>, inhabited the foothills and crags around the base of the mountain and sought to gain more control within the city. The third faction, the <a href="/Dark_Iron_Clan" class="mw-redirect" title="Dark Iron Clan">Dark Iron</a> clan, was ruled by the <a href="/Sorcerer-Thane_Thaurissan" title="Sorcerer-Thane Thaurissan">sorcerer-thane Thaurissan</a>. The Dark Irons hid within the deepest shadows under the mountain and plotted against both their Bronzebeard and the Wildhammer cousins. </p><p>For a time the three factions kept a tenuous peace, but tensions erupted when High King Anvilmar passed away from old age. The three ruling clans went to war for control of Ironforge itself. The dwarf civil war raged under the earth for many years. Eventually the Bronzebeards, who had the largest standing army, banished the Dark Irons and Wildhammers from under the mountain. </p><p>Khardros and his Wildhammer warriors traveled north through the barrier gates of <a href="/Dun_Algaz" title="Dun Algaz">Dun Algaz</a>, and they founded their own kingdom within the distant peak of <a href="/Grim_Batol" title="Grim Batol">Grim Batol</a>. There, the Wildhammers thrived and rebuilt their stores of treasure. Thaurissan and his Dark Irons did not fare as well. Humiliated and enraged by their defeat, they vowed revenge against Ironforge. Leading his people far to the south, Thaurissan founded a city (which he named after himself) within the beautiful <a href="/Redridge_Mountains" title="Redridge Mountains">Redridge Mountains</a>. Prosperity and the passing of years did little to ease the Dark Iron\'s rancor toward their cousins. Thaurissan and his sorceress wife, <a href="/Modgud" title="Modgud">Modgud</a>, launched a two-pronged assault against both Ironforge and Grim Batol. The Dark Irons were intent on claiming all of Khaz Modan for their own. </p></BODY></HTML>'
    L["War of the Three Hammers page 2"] =
        '<HTML><BODY><p>The Dark Iron armies smashed against their cousins\' strongholds and very nearly took both kingdoms. However, Madoran Bronzebeard ultimately led his clan to a decisive victory over Thaurissan\'s sorcerous army. Thaurissan and his servants fled back to the safety of their city, unaware of the events transpiring at Grim Batol, where Modgud\'s army would fare no better against Khardros and his Wildhammer warriors. </p><p>As she confronted the enemy warriors, Modgud used her powers to strike fear into their hearts. Shadows moved at her command, and dark things crawled up from the depths of the earth to stalk the Wildhammers in their own halls. Eventually Modgud broke through the gates and laid siege to the fortress itself. The Wildhammers fought desperately, Khardros himself wading through the roiling masses to slay the sorceress queen. With their queen lost, the Dark Irons fled before the fury of the Wildhammers. They raced south toward their king\'s stronghold, only to meet the armies of Ironforge, which had come to aid Grim Batol. Crushed between two armies, the remaining Dark Iron forces were utterly destroyed. </p><p>The combined armies of Ironforge and Grim Batol then turned south, intent on destroying Thaurissan and his Dark Irons once and for all. They had not gone far when Thaurissan\'s fury resulted in a spell of cataclysmic proportions. Seeking to summon a supernatural minion that would ensure his victory, Thaurissan called upon the ancient powers sleeping beneath the world. To his shock, and ultimately his doom, the creature that emerged was more terrible than any nightmare he could have imagined. </p><p><a href="/Ragnaros" title="Ragnaros">Ragnaros</a> the Firelord, immortal lord of all fire elementals, had been banished by the <a href="/Titan" title="Titan">Titans</a> when the world was young. Now, freed by Thaurissan\'s call, Ragnaros erupted into being once again. Ragnaros\' apocalyptic rebirth into <a href="/Azeroth" title="Azeroth">Azeroth</a> shattered the Redridge Mountains and created a raging volcano at the center of the devastation. The volcano, known as <a href="/Blackrock_Spire" title="Blackrock Spire">Blackrock Spire</a>, was bordered by the <a href="/Searing_Gorge" title="Searing Gorge">Searing Gorge</a> to the north and the <a href="/Burning_Steppes" title="Burning Steppes">Burning Steppes</a> to the south. Though Thaurissan was killed by the forces he had unleashed, his surviving brethren were ultimately enslaved by Ragnaros and his elementals. They remain within the Spire to this day. </p><p>Witnessing the horrific devastation and the fires spreading across the southern mountains, King Madoran and King Khardros halted their armies and hastily turned back towards their kingdoms, unwilling to face the awesome wrath of Ragnaros. </p></BODY></HTML>'
    L["War of the Three Hammers page 3"] =
        '<HTML><BODY><p>The Bronzebeards returned to Ironforge and rebuilt their glorious city. The Wildhammers also returned home to Grim Batol. However, the death of the Modgud had left an evil stain on the mountain fortress, and the Wildhammers found it uninhabitable. They were bitter in their hearts over the loss of their beloved home. King Bronzebeard offered the Wildhammers a place to live within the borders of Ironforge, but the Wildhammers steadfastly refused. Khardros took his people north towards the lands of <a href="/Lordaeron" title="Lordaeron">Lordaeron</a>. Settling within the lush forests of the <a href="/Hinterlands" title="Hinterlands">Hinterlands</a>, the Wildhammers crafted the city of <a href="/Aerie_Peak" title="Aerie Peak">Aerie Peak</a>, where the Wildhammers grew closer to nature and even bonded with the mighty <a href="/Gryphon" title="Gryphon">gryphons</a> of the area. </p><p>Seeking to retain relations and trade with their cousins, the dwarves of Ironforge constructed two massive arches, the <a href="/Thandol_Span" title="Thandol Span">Thandol Span</a>, to bridge the gap between Khaz Modan and Lordaeron. Bolstered by mutual trade, the two kingdoms prospered. After the deaths of Madoran and Khardros, their sons jointly commissioned two great statues in honor of their fathers. The two statues would stand guard over the pass into the southlands, which had become volcanic in the wake of Ragnaros\' scorching presence. They served as both a warning to all who would attack the dwarven kingdoms, and as a reminder of what price the Dark Irons paid for their crimes. </p><p>The two kingdoms retained close ties for some years, but the Wildhammers were much changed by the horrors they witnessed at Grim Batol. They took to living above ground on the slopes of Aerie Peak, instead of carving a vast kingdom within the mountain. The ideological differences between the two remaining dwarven clans eventually led to their parting of ways.</p></BODY></HTML>'
end
